//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InetTarif.rc
//
#define IDCANCEL2                       3
#define IDADD                           3
#define IDCANCEL3                       4
#define IDDEL                           4
#define IDC_BUTEDIT                     4
#define IDEDIT                          5
#define IDACTIVE                        6
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_INETTARIF_DIALOG            102
#define IDS_PROPSHT_CAPTION             103
#define IDD_PROPPAGE1                   104
#define IDD_PROPPAGE2                   105
#define IDB_LIGHTBULB                   110
#define IDD_TIP                         111
#define CG_IDS_TIPOFTHEDAY              112
#define CG_IDS_TIPOFTHEDAYMENU          113
#define CG_IDS_DIDYOUKNOW               114
#define CG_IDS_FILE_ABSENT              115
#define CG_IDP_FILE_CORRUPT             116
#define CG_IDS_TIPOFTHEDAYHELP          117
#define CG_IDS_PHYSICAL_MEM             118
#define CG_IDS_DISK_SPACE               119
#define CG_IDS_DISK_SPACE_UNAVAIL       120
#define IDR_HTML_DIALOG2                126
#define IDR_MAINFRAME                   128
#define IDR_MAINMENU                    129
#define IDD_PSWDIALOG                   131
#define IDD_SETUPDIALOG                 132
#define IDD_TARIFDLG                    138
#define IDB_MYLOGO                      139
#define IDB_LOGO                        148
#define IDB_UKRTELECOM                  149
#define IDD_REPORTDLG                   152
#define IDD_RASCHDIALOG                 154
#define IDB_BITMAP3                     157
#define IDB_BITMAP4                     158
#define IDB_BITMAP8                     162
#define IDB_BITMAP1                     164
#define IDD_NAMECOMPUTER                172
#define IDD_BUTTONBLOCK                 174
#define IDD_CHANGEPAS                   177
#define IDD_ADMIN                       178
#define IDB_GROUP                       180
#define IDB_USER                        181
#define IDI_GROUP                       182
#define IDI_USER                        183
#define IDR_ACCELERATOR                 187
#define IDI_ICON1                       189
#define IDI_ICON2                       190
#define IDI_BADUSER                     194
#define IDD_USER                        196
#define IDB_BADUSER                     197
#define IDD_HOLIDAYS                    198
#define IDI_PLUS                        200
#define IDI_MINUS                       201
#define IDI_KEY                         202
#define IDI_ADMIN                       203
#define IDD_MENAGE                      204
#define IDD_MANAGE                      204
#define IDI_COMP                        206
#define IDI_COMP1                       208
#define IDB_LOGOM                       209
#define IDB_HTML                        210
#define IDI_HTML                        212
#define IDB_TLCLOGO                     226
#define IDI_STATUS                      227
#define IDI_STATUS_ERROR                228
#define IDB_BITMAP2                     233
#define IDD_STAT                        234
#define IDD_TARIF                       236
#define IDD_NEW_EDIT                    237
#define IDD_TARIF_EDIT                  237
#define IDD_CHEK                        238
#define IDD_VNESENIE                    240
#define IDD_SETSEANS                    243
#define IDD_DIALOG1                     248
#define IDD_STUDENT                     248
#define IDD_IZYATIE                     249
#define IDR_LISTMNU                     250
#define IDD_REPLOG                      253
#define IDD_DELREP                      254
#define IDD_SVREP                       255
#define IDD_SESSMOVE                    256
#define IDD_DIALOG2                     257
#define IDC_BULB                        1000
#define IDC_STARTUP                     1001
#define IDC_NEXTTIP                     1002
#define IDC_TIPSTRING                   1004
#define IDC_BUTTON4                     1006
#define IDC_SVEXCEL                     1006
#define IDC_PANEL                       1007
#define IDC_PASSWEDIT                   1009
#define IDC_IDEDIT                      1010
#define IDC_CASSACHECK                  1014
#define IDC_CASSACOMBO                  1015
#define IDC_MSFLEXGRID                  1016
#define IDC_COMPCOMBO                   1017
#define IDC_RTS                         1018
#define IDC_COUNTCOMPORT                1020
#define IDC_COMPORTSPIN                 1021
#define IDC_BOTH                        1022
#define IDC_COUNTCOMP                   1023
#define IDC_COMPSPIN                    1024
#define IDC_COMBO                       1025
#define IDC_NAME                        1026
#define IDC_TARIF                       1028
#define IDC_TARIF2                      1029
#define IDC_SPIN                        1030
#define IDC_SPIN1                       1030
#define IDC_SPIN2                       1031
#define IDC_TARIF3                      1032
#define IDC_SPIN3                       1033
#define IDC_TARIF4                      1034
#define IDC_SPIN4                       1035
#define IDC_SHOW                        1036
#define IDC_TARIF5                      1036
#define IDC_PRINT                       1037
#define IDC_SPIN5                       1037
#define IDC_FROM                        1038
#define IDC_TARIF6                      1038
#define IDC_TO                          1039
#define IDC_SPIN6                       1039
#define IDC_ISPTIME                     1040
#define IDC_BILLPATH                    1040
#define IDC_TARIF7                      1040
#define IDC_ZALOG                       1041
#define IDC_INAME                       1041
#define IDC_SPIN7                       1041
#define IDC_INUSE                       1042
#define IDC_INOMER                      1042
#define IDC_WWW                         1042
#define IDC_TARIF8                      1042
#define IDC_OSTATOK                     1043
#define IDC_WWW1                        1043
#define IDC_SHAREPATH                   1043
#define IDC_SPIN8                       1043
#define IDC_GATEWAYNAME                 1044
#define IDC_TARIF9                      1044
#define IDC_CurNds                      1044
#define IDC_COMP                        1046
#define IDC_ATTACH                      1047
#define IDC_STATIC1                     1048
#define IDC_STATIC2                     1049
#define IDC_STATIC3                     1050
#define IDC_STATIC4                     1051
#define IDC_STATIC5                     1052
#define IDC_STATIC6                     1053
#define IDC_STATIC7                     1054
#define IDC_STATIC8                     1055
#define IDC_STATIC9                     1056
#define IDC_STATIC10                    1057
#define IDC_USECOMCHECK                 1058
#define IDC_LOCKEDIT                    1059
#define IDC_UNLOCKEDIT                  1060
#define IDC_NAMEEDIT                    1060
#define IDC_CHECK1                      1061
#define IDC_CHECK2                      1062
#define IDC_OST                         1062
#define IDC_CHECK3                      1063
#define IDC_CHECKINET                   1063
#define IDC_CHECK4                      1064
#define IDC_CHECKEXPLORER               1064
#define IDC_CHECK5                      1065
#define IDC_CHECK6                      1066
#define IDC_CHECK7                      1067
#define IDC_CHECK8                      1068
#define IDC_CHECK9                      1069
#define IDC_CHECK10                     1070
#define IDC_STATICS                     1073
#define IDC_CHECKPIPES                  1074
#define IDC_TARIF1                      1075
#define IDC_CHECK                       1076
#define IDC_PWDOLD                      1080
#define IDC_PWDNEW                      1081
#define IDC_TREE1                       1081
#define IDC_TREE                        1081
#define IDC_PWDREP                      1082
#define IDC_RES                         1082
#define IDC_IPADDRESS1                  1084
#define IDC_ID                          1085
#define IDC_SUPER                       1087
#define IDC_ADMIN                       1088
#define IDC_USER                        1089
#define IDC_CREATOR                     1090
#define IDC_CHANGE                      1091
#define IDC_COM                         1092
#define IDC_CALENDAR                    1096
#define IDC_HOLIDAYS                    1098
#define IDC_DATE                        1099
#define IDC_STATICPANEL                 1100
#define IDC_REM                         1100
#define IDC_STATICPANEL2                1101
#define IDC_DEL                         1101
#define IDC_STATICPANEL3                1102
#define IDC_INS                         1102
#define IDC_OPERATION                   1102
#define IDC_STATICPANEL4                1103
#define IDC_STATICPANEL5                1104
#define IDC_STATICPANEL6                1105
#define IDC_ALL                         1105
#define IDC_STATICPANEL7                1106
#define IDC_HOLIDAY                     1106
#define IDC_STATICPANEL8                1107
#define IDC_MANAGE                      1107
#define IDC_STATICPANEL9                1108
#define IDC_UNBLOCK                     1108
#define IDC_STATICPANEL10               1109
#define IDC_BLOCK                       1109
#define IDC_STATICPANEL14               1110
#define IDC_REBOOT                      1110
#define IDC_STATICPANEL11               1111
#define IDC_SHUTDOWN                    1111
#define IDC_INETON                      1112
#define IDC_INETOFF                     1113
#define IDC_CLIENT                      1114
#define IDC_STATICPANEL12               1116
#define IDC_GRID                        1116
#define IDC_TYPE                        1119
#define IDC_STATICPANEL13               1121
#define IDC_DATETIMEPICKER1             1121
#define IDC_DTFROM                      1121
#define IDC_DATETIMEPICKER2             1122
#define IDC_DTTO                        1122
#define IDC_INET                        1125
#define IDC_WORK                        1126
#define IDC_EDIT1                       1127
#define IDC_DOPKOL                      1127
#define IDC_VNESS                       1127
#define IDC_EDIT2                       1128
#define IDC_KOD                         1128
#define IDC_DATA                        1128
#define IDC_HOUR                        1128
#define IDC_TAR                         1128
#define IDC_EDIT3                       1129
#define IDC_MIN                         1129
#define IDC_EDIT4                       1130
#define IDC_ED                          1130
#define IDC_DOPTAR                      1131
#define IDC_RF2160                      1132
#define IDC_TARNAME                     1132
#define IDC_DOPUSL                      1136
#define IDC_TEXT                        1147
#define IDC_DOPSUMM                     1148
#define IDC_LIST                        1149
#define IDC_NAL                         1151
#define IDC_RADIO2                      1152
#define IDC_TIME                        1152
#define IDC_RASCH                       1153
#define IDC_CAPDATA                     1154
#define IDC_RASHTYPE                    1155
#define IDC_CHENGDATA                   1159
#define IDC_CHENGHOUR                   1159
#define IDC_SDACHA                      1160
#define IDC_CHENGDATA2                  1161
#define IDC_COLCOMP                     1162
#define ID_NEWSEANS                     1163
#define IDC_CHENGMIN                    1164
#define IDC_STATCOMBO                   1164
#define IDC_PRIEM                       1166
#define IDC_REDREPLOG                   1168
#define IDC_EDREPLOG                    1169
#define IDC_SELALL                      1170
#define IDC_UNSEL                       1171
#define IDC_BUTADD                      1172
#define IDC_BUTDELETE                   1173
#define IDC_RFCODE                      1176
#define IDC_RFNAME                      1177
#define IDC_BTNRFSH                     1179
#define IDC_PRIN_UAH                    1180
#define IDC_ZALOG_UAH                   1181
#define IDC_RFRATE                      1183
#define IDC_SVSHOW                      1184
#define IDC_TARTYPE                     1184
#define IDC_BUTTON2                     1185
#define IDCOK                           1186
#define IDC_IZ                          1188
#define IDC_STATIC12                    1189
#define IDC_STATIC11                    1190
#define IDC_ZALOGEDIT                   1200
#define IDC_ZALOGEDIT2                  1201
#define IDC_ZALOGEDIT3                  1202
#define IDC_ZALOGEDIT4                  1203
#define IDC_ZALOGEDIT5                  1204
#define IDC_ZALOGEDIT6                  1205
#define IDC_ZALOGEDIT7                  1206
#define IDC_ZALOGEDIT8                  1207
#define IDC_ZALOGEDIT9                  1208
#define IDC_ZALOGEDIT10                 1209
#define IDC_ZALOGBUTTON                 1300
#define IDC_ZALOGBUTTON2                1301
#define IDC_ZALOGBUTTON3                1302
#define IDC_ZALOGBUTTON4                1303
#define IDC_ZALOGBUTTON5                1304
#define IDC_ZALOGBUTTON6                1305
#define IDC_ZALOGBUTTON7                1306
#define IDC_ZALOGBUTTON8                1307
#define IDC_ZALOGBUTTON9                1308
#define IDC_ZALOGBUTTON10               1309
#define IDC_RASBUTTON                   1400
#define IDC_RASBUTTON2                  1401
#define IDC_RASBUTTON3                  1402
#define IDC_RASBUTTON4                  1403
#define IDC_RASBUTTON5                  1404
#define IDC_RASBUTTON6                  1405
#define IDC_RASBUTTON7                  1406
#define IDC_RASBUTTON8                  1407
#define IDC_RASBUTTON9                  1408
#define IDC_RASBUTTON10                 1409
#define IDC_PROGRESS                    1500
#define IDC_PROGRESS2                   1501
#define IDC_PROGRESS1                   1501
#define IDC_PROGRESS3                   1502
#define IDC_PROGRESS4                   1503
#define IDC_PROGRESS5                   1504
#define IDC_PROGRESS6                   1505
#define IDC_PROGRESS7                   1506
#define IDC_PROGRESS8                   1507
#define IDC_PROGRESS9                   1508
#define IDC_PROGRESS10                  1509
#define IDC_COUNTTIME                   1600
#define IDC_COUNTTIME2                  1601
#define IDC_COUNTTIME3                  1602
#define IDC_COUNTTIME4                  1603
#define IDC_COUNTTIME5                  1604
#define IDC_COUNTTIME6                  1605
#define IDC_COUNTTIME7                  1606
#define IDC_COUNTTIME8                  1607
#define IDC_COUNTTIME9                  1608
#define IDC_COUNTTIME10                 1609
#define IDC_CHECKS                      1700
#define IDC_CHECKS2                     1701
#define IDC_CHECKS3                     1702
#define IDC_CHECKS4                     1703
#define IDC_CHECKS5                     1704
#define IDC_CHECKS6                     1705
#define IDC_CHECKS7                     1706
#define IDC_CHECKS8                     1707
#define IDC_CHECKS9                     1708
#define IDC_CHECKS10                    1709
#define IDC_FIO                         1800
#define IDC_FIO2                        1801
#define IDC_FIO3                        1802
#define IDC_FIO4                        1803
#define IDC_FIO5                        1804
#define IDC_FIO6                        1805
#define IDC_FIO7                        1806
#define IDC_FIO8                        1807
#define IDC_FIO9                        1808
#define IDC_FIO10                       1809
#define IDC_NUM                         1900
#define IDC_NUM2                        1901
#define IDC_NUM3                        1902
#define IDC_NUM4                        1903
#define IDC_NUM5                        1904
#define IDC_NUM6                        1905
#define IDC_NUM7                        1906
#define IDC_NUM8                        1907
#define IDC_NUM9                        1908
#define IDC_NUM10                       1909
#define PUSK                            3000
#define STOP                            3001
#define RASCH                           3002
#define ID_EXIT                         32771
#define ID_TIP                          32772
#define ID_TARIF                        32783
#define ID_COM                          32784
#define ID_DAYOFF                       32787
#define ID_MENUITEMBLOCK                32790
#define ID_ADMIN                        32791
#define ID_MENUITEM32793                32793
#define ID_CHANGEPASS                   32793
#define ID_LOGOFF                       32795
#define ID_HOLIDAYS                     32796
#define ID_SMENA                        32797
#define ID_MANAGE                       32798
#define ID_MANIP                        32799
#define ID_CHEK                         32800
#define ID_XOTCHET_T                    32805
#define ID_XOTCHET                      32808
#define ID_VNESENIE                     32809
#define ID_MOTCHET                      32810
#define ID_OTKR                         32811
#define ID_ZOTCHET                      32812
#define ID_ZOTCHET_T                    32813
#define ID_SETTARIF                     32814
#define ID_IZYATIE                      32819
#define RESET                           32820
#define SHUTDOWN                        32821
#define ID_Menu                         32822
#define ID_ABOUT                        32823
#define ID_PAYMENT                      32825
#define ID_DELREP                       32827
#define ID_32828                        32828
#define ID_REMOVEPSSBR                  32829
#define IDD_SV                          32830
#define IDD_SVPAYREP                    32831
#define ID_32832                        32832
#define BREAKST                         32833
#define ID_32834                        32834
#define WORKST                          32835
#define ID_ITEMS_32836                  32836
#define PROLONG                         32837
#define ID_ITEMS_32838                  32838
#define MOVE                            32839
#define ID_ITEMS_32840                  32840
#define OSTANOV                         32841
#define ID_INTERNET                     32842
#define ID_ITEMS_32843                  32843
#define RASCH_CARD                      32844

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        258
#define _APS_NEXT_COMMAND_VALUE         32845
#define _APS_NEXT_CONTROL_VALUE         1191
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
